index:
    path: /
    controller: App\Controller\Index::index

services:
    path: /services
    controller: App\Controller\Services::index

form:
    path: /form
    methods: GET
    controller: App\Controller\Form::index

createOrder:
    path: /form
    methods: POST
    controller: App\Controller\Form::createOrder

confirmation:
    path: /confirmation
    controller: App\Controller\Form::confirmation

enter:
    path: /enter
    methods: GET
    controller: App\Controller\Enter::index

create_user:
    path: /registration
    methods: POST
    controller: App\Controller\Registration::createUser

authUser:
    path: /enter
    methods: POST
    controller: App\Controller\Enter::authUser

logout:
    path: /logout
    controller: App\Controller\Enter::logout

registration:
    path: /registration
    methods: GET
    controller: App\Controller\Registration::index
