index:
    path: /
    controller: App\Controller\Index::index

services:
    path: /services
    controller: App\Controller\Services::index

form:
    path: /form
    methods: GET
    controller: App\Controller\Form::index

createOrder:
    path: /form
    methods: POST
    controller: App\Controller\Form::createOrder

confirmation:
    path: /confirmation
    controller: App\Controller\Form::confirmation
