index:
    path: /
    controller: App\Controller\Index::index

services:
    path: /services
    controller: App\Controller\Services::index

form:
    path: /form
    controller: App\Controller\Form::index
